receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health/status"
exporters:
  debug: {}
  # Export metrics to Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "product-aggregator"

  otlphttp:
    endpoint: "http://192.168.100.10:3100/otlp"  # Loki OTLP Ingest API

  # Export traces to Tempo
  otlp/tempo:
    endpoint: "192.168.100.10:14317" # VVI changed default port
    tls:
      insecure: true

service:
  telemetry:
      logs:
        level: debug
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug,otlp/tempo]
    metrics:
      receivers: [otlp]
      exporters: [debug,prometheus]
    logs:
      receivers: [otlp]
      exporters: [debug,otlphttp]
#      exporters: [debug,loki]
