otel:
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://${OTEL_COLLECTOR_HOST}:4317

server:
  port: 8081

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: ${OTEL_SERVICE_NAME:OTEL_SERVICE_NAME_ENV_VARIABLE_MISSING}
  reactor:
    context-propagation: AUTO

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:DB_HOST_MISSING}:5432/${DB_NAME:DB_NAME_MISSING}
    username: ${DB_USER:DB_USER_MISSING}
    password: ${DB_PASS:DB_PASS_MISSING}
  sql:
    init:
      mode: always  # Or 'never' to avoid schema initialization

management:
  otlp:
    metrics:
      export:
        enabled: true
        histogram-flavor: explicit_bucket_histogram
        url: http://${OTEL_COLLECTOR_HOST}:4317  # gRPC port (4317)
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  metrics:
    enable:
      service-name-prefix: false
