spring:
  application:
    name: product-review
  grpc:
    server:
      port: 6565
  sql:
    init:
      mode: always
      encoding: UTF-8
      data-locations: classpath:data.sql
      continue-on-error: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: myuser
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000