otel:
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://${OTEL_COLLECTOR_HOST}:4317

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: ${OTEL_SERVICE_NAME:OTEL_SERVICE_NAME_ENV_VARIABLE_MISSING}
  grpc:
    server:
      port: 6565
  sql:
    init:
      mode: always
      encoding: UTF-8
      data-locations: classpath:data.sql
      continue-on-error: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:DB_HOST_MISSING}:5432/${DB_NAME:DB_NAME_MISSING}
    username: ${DB_USER:DB_USER_MISSING}
    password: ${DB_PASS:DB_PASS_MISSING}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000

management:
  otlp:
    metrics:
      export:
        enabled: true
        histogram-flavor: explicit_bucket_histogram
        url: http://otel-collector:4317  # gRPC port (4317)
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics,trace,logfile
  metrics:
    enable:
      resilience4j.circuitbreaker: true
