version: '3.9'

services:
  grafana:
    image: grafana/grafana:11.5.3
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - tempo


  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount your custom config file
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config.yml:/etc/tempo.yaml
#      - ./tempo-data:/var/tempo
#    ports:
#      - "14268:14268"  # jaeger ingest
#      - "3200:3200"   # tempo
#      - "9095:9095" # tempo grpc
#      - "4317:4317"  # otlp grpc
#      - "4318:4318"  # otlp http
#      - "9411:9411"   # zipkin
#      -
    ports:
      - "14317:4317"  # OTLP gRPC
      - "3200:3200"  # Tempo UI

